# Generated by Django 5.2.8 on 2025-11-18 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categorias_ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_minutos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id_tecnica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnica', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaingrediente')),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
        migrations.CreateModel(
            name='EtapaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_etapa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etapa')),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Canasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(max_length=30)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.ingrediente')),
            ],
            options={
                'verbose_name_plural': 'Canasta',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_receta', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_preparacion_minutos', models.IntegerField(blank=True, null=True)),
                ('porciones', models.IntegerField(blank=True, null=True)),
                ('detalle_montaje', models.TextField(blank=True, null=True)),
                ('justificacion_tecnica', models.TextField(blank=True, null=True)),
                ('justificacion_comercial', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_etapa', models.IntegerField(blank=True, null=True)),
                ('id_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etapa')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingrediente')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
                ('id_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecnica')),
            ],
        ),
    ]
